#81:  HttpRequestService ability to work with multipart #81
RonasIT/laravel-helpers pull request #112
Opened 2024-04-13 12:48 UTC by Adil9994

2024-04-16 05:49 UTC, DenTray requested changes

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +        Arr::forget($this->options, 'headers.content-type');
please increase Laravel min version requirements up to 5.7

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +    public function parseMultipart(string $content): StreamedPart
```suggestion
    public function multipart(): Generator
```

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +        return app()->makeWith(StreamedPart::class, ['stream' => $stream]);
```suggestion
        return app()
                ->makeWith(StreamedPart::class, ['stream' => $stream])
                ->getParts();
```

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +    public function parseMultipart(string $content): StreamedPart
let's get content from the response instead

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +    protected function getMultipartOptionReplacement(array $data): array
```suggestion
    protected function convertToMultipart(array $data): array
```

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +        Arr::forget($this->options, 'headers.content-type');
let's move this logic out of this function

2024-04-16 05:49 UTC, DenTray commented on src/Services/HttpRequestService.php
> +    protected function getArrayMultipartOptionReplacement(string $parentKey, array $items): array
please keep only one method `convertToMultipart` with optional `parentKey` arg

2025-02-26 04:02 UTC, DenTray requested changes

2025-02-26 04:02 UTC, DenTray commented on src/Services/HttpRequestService.php
> +    public function multipart(string $content): array
content should be received from the `response` class field as it implemented in `json` method

2025-02-26 04:02 UTC, DenTray commented on tests/fixtures/MailsMockTraitTest/test_mail_with_global_export.html
> +"test_mail_with_global_export_example"
is this fixture using anywhere?

2025-02-28 13:37 UTC, RGO230 commented on src/Services/HttpRequestService.php
> +            Arr::forget($this->options, 'headers.content-type');
![image](https://github.com/user-attachments/assets/8842dfe9-d9b4-4dfa-bfdd-cdba5a4efe64)

how correct complete this thread?

2025-03-03 11:12 UTC, RGO230 commented on src/Services/HttpRequestService.php
> +    public function multipart(string $content): array
in this context, $content is equal this data from fixture:
![image](https://github.com/user-attachments/assets/58bed53a-6bc4-4d62-8e93-284e26793c7a)

2025-03-05 07:11 UTC, DenTray commented on src/Services/HttpRequestService.php
> +            Arr::forget($this->options, 'headers.content-type');
if presented header break the multipart request - we need to remove it, but if it will works as expected with the header - I not sure we should remove it

2025-03-21 08:45 UTC, NikitaYakovlev commented on src/Services/HttpRequestService.php
> +            Arr::forget($this->options, 'headers.content-type');
We need to remove this header because the Guzzle Client adds this header with the correct boundary. If we leave it, it might break the logic of the external API.

2025-03-25 05:44 UTC, DenTray approved these changes

2025-03-25 05:44 UTC, DenTray commented on src/Services/HttpRequestService.php
> +            Arr::forget($this->options, 'headers.content-type');
@NikitaYakovlev thanks a lot!

2025-03-25 05:44 UTC, DenTray commented on src/Services/HttpRequestService.php
> +        return $options;
```suggestion
        $result = [];

        foreach ($data as $key => $value) {
            $preparedKey = is_int($key) || is_null($parentKey)
                ? $key
                : "{$parentKey}[{$key}]";

            if (is_array($value)) {
                $result = array_merge($result, $this->convertToMultipart($value, $preparedKey));
            } else {
                $result[] = [
                    'name' => $preparedKey,
                    'contents' => $value,
                ];
            }
        }

        return $result;
```

2025-03-25 05:46 UTC, merged