Clone user pre send to actingas
RonasIT/laravel-helpers pull request #121
Opened 2024-05-17 07:03 UTC by AZabolotnikov

added method actingAs to trait AuthTestTrait, this solution solve problem when test user define as static in tests. This protect for change user object on batch testing.

2024-05-17 11:43 UTC, DenTray requested changes

2024-05-17 11:43 UTC, DenTray commented on tests/AuthTestTraitTest.php
> +        $this->assertEquals(0, Auth::user()->someIntProperty);
let's try to test it like this

```suggestion
        $mockedUser = new MockAuthUser();

        $this->actingAs($mockedUser);

        $this-> assertNotSame($mockedUser, Auth::user());
```

2024-05-20 09:23 UTC, AZabolotnikov commented on tests/AuthTestTraitTest.php
> +        $this->assertEquals(0, Auth::user()->someIntProperty);
This work is great! Thanks.

2024-05-20 09:26 UTC, DenTray requested changes

2024-05-20 09:26 UTC, DenTray commented on tests/support/Mock/MockAuthUser.php
> +
```suggestion
```

2024-05-20 09:28 UTC, DenTray approved these changes

2024-05-20 09:28 UTC, merged