#117: Implement TableTestState class
RonasIT/laravel-helpers pull request #156
Opened 2024-11-28 14:07 UTC by yogyrton

2024-11-29 06:16 UTC, aizlee requested changes

2024-12-04 03:59 UTC, aizlee requested changes

2024-12-04 03:59 UTC, aizlee commented on src/Tests/TableTestState.php
> +    }
```suggestion
    public function __construct(
        string $tableName,
        array $jsonFields = [],
        string $connectionName = null,
    ) {
        parent::__construct(
            tableName: $tableName,
            jsonFields: $jsonFields,
            connectionName: $connectionName ?? DB::getDefaultConnection(),
        );
    }
```

`connectionName` must be an argument in the constructor. In this case, we can specify any connection we need.

2024-12-04 03:59 UTC, aizlee commented on tests/support/Traits/TableTestStateMockTrait.php
> +trait TableTestStateMockTrait
`TableTestStateMockTrait` and `ModelTestStateMockTrait` are very similar. Can we combine them?

2024-12-09 08:51 UTC, DenTray requested changes

2024-12-09 16:00 UTC, yogyrton commented on src/Tests/ModelTestState.php
>          $this->model = new $modelClassName();
We need to store the model in a property because it is used in `getModelJSONFields()`

2024-12-09 16:36 UTC, yogyrton commented on tests/ModelTestStateTest.php
> +use RonasIT\Support\Tests\Support\Traits\BaseTestStateMockTrait;
it is used in ModelTestStateTest and TableTestStateTest

2024-12-12 00:38 UTC, DenTray approved these changes

2024-12-12 00:38 UTC, DenTray commented on src/Tests/ModelTestState.php
> +            connectionName: $model->getConnectionName($model),
```suggestion
            connectionName: $model->getConnectionName(),
```

2024-12-12 00:38 UTC, DenTray commented on src/Tests/TableTestState.php
> +    protected ?string $connectionName;
```suggestion
    protected string $connectionName;
```

2024-12-12 00:38 UTC, DenTray commented on tests/support/Traits/TableTestStateMockTrait.php
> +    protected function mockGettingDatasetForChanges(Collection $responseMock, Collection $initialState, string $tableName): void {
```suggestion
    protected function mockGettingDatasetForChanges(Collection $responseMock, Collection $initialState, string $tableName): void
    {
```

2024-12-12 00:40 UTC, DenTray approved these changes

2024-12-12 00:40 UTC, DenTray commented on tests/support/Traits/TableTestStateMockTrait.php
> +
```suggestion
```

2024-12-12 00:40 UTC, DenTray approved these changes

2024-12-12 00:52 UTC, DenTray approved these changes

2024-12-12 00:52 UTC, DenTray commented on src/Tests/TableTestState.php
> +    protected string $connectionName;
```suggestion
    protected ?string $connectionName;
```

2024-12-12 00:52 UTC, DenTray approved these changes

2024-12-12 00:55 UTC, merged