#145: Mock class not assert arguments with the empty arg list
RonasIT/laravel-helpers pull request #157
Opened 2024-12-03 13:09 UTC by yogyrton

https://github.com/RonasIT/laravel-helpers/issues/145

2024-12-05 04:56 UTC, aizlee requested changes

2024-12-05 04:56 UTC, aizlee commented on src/Traits/MockTrait.php
> +        $expected = array_merge($expected, array_fill(0, $actualCount - $expectedCount, 'optionalParameter'));
```suggestion
        $expected = array_pad($expected, $actualCount, 'optionalParameter');
```

2024-12-05 04:56 UTC, aizlee commented on src/Traits/MockTrait.php
> +            $requiredParametersCount = $actualCount - $optionalParametersCount;
```suggestion
            $requiredParametersCount = count(array_filter($actual, fn ($item) => $item !== 'optionalParameter'));
```

2024-12-05 04:56 UTC, aizlee commented on src/Traits/MockTrait.php
> +            $requiredParametersCount = $actualCount - $optionalParametersCount;
@yogyrton  Could we use `optionalParameter` as constant of class?

2024-12-06 03:47 UTC, aizlee requested changes

2024-12-06 03:47 UTC, aizlee commented on src/Traits/MockTrait.php
> +    protected const OPTIONAL_PARAMETER = 'optionalParameter';
```suggestion
    protected const OPTIONAL_ARGUMENT_NAME = 'optionalParameter';
```

2024-12-09 10:45 UTC, DenTray approved these changes

2024-12-09 10:48 UTC, aizlee approved these changes

2024-12-09 10:54 UTC, merged