#140: Global export mode not affect for email testing
RonasIT/laravel-helpers pull request #159
Opened 2024-12-05 08:41 UTC by yogyrton

https://github.com/RonasIT/laravel-helpers/issues/140

2024-12-06 05:11 UTC, aizlee requested changes

2024-12-06 05:11 UTC, aizlee commented on src/Traits/MailsMockTrait.php
> +        if (!$exportMode) {
Need to move `globalMode` checking to the `MailsMockTrait.assertFixture` method.

```
$globalExportMode = $this->globalExportMode ?? false;

if ($exportMode || $globalExportMode) {
    $this->exportContent($mailContent, $expectedMailData['fixture']);
}
```

2024-12-09 10:48 UTC, aizlee approved these changes

2024-12-09 10:53 UTC, DenTray requested changes

2024-12-09 10:53 UTC, DenTray commented on tests/MailsMockTraitTest.php
> +    public function testMailWithGlobalExportMod()
```suggestion
    public function testMailWithGlobalExportMode()
```

2024-12-09 10:53 UTC, DenTray commented on tests/MailsMockTraitTest.php
> +            $this->mockedMail('test@mail.com', 'test_mail_with_export.html', 'Test Subject'),
```suggestion
            $this->mockedMail('test@mail.com', 'test_mail_with_global_export.html', 'Test Subject'),
```

2024-12-12 01:12 UTC, DenTray requested changes

2024-12-12 01:12 UTC, DenTray commented on tests/MailsMockTraitTest.php
> +        $this->assertFileExists($this->getFixturePath('test_mail_with_export.html'));
why you checking `test_mail_with_export.html` file, but asserting content with the `test_mail_with_global_export.html`?

2024-12-12 01:12 UTC, DenTray commented on tests/fixtures/MailsMockTraitTest/test_mail_with_global_export.html
> +<div>
you using this fixture to check that globa export mode works fine and create file if it not exists. If you'll commit this file to git - test will always be successful completed even if global export mode will be broken

2024-12-17 10:37 UTC, closed without merging