fix: insert method with fillable of the model
RonasIT/laravel-helpers pull request #178
Opened 2024-12-26 10:23 UTC by yogyrton

https://github.com/RonasIT/laravel-helpers/issues/165#issuecomment-2562139311

2025-01-09 03:46 UTC, DenTray requested changes

2025-01-09 03:46 UTC, DenTray commented on src/Traits/EntityControlTrait.php
> +            });
as discussed, no need to map data into Carbon instance, developer should fill timestamps with the correct data type in case he fill timestamps manually

2025-01-09 03:46 UTC, DenTray commented on tests/EntityControlTraitTest.php
> +                'created_at' => '1999-01-01',
let's keep already existed test cases as are and implement separate test case for filling timestamps manually

2025-01-09 08:02 UTC, DenTray requested changes

2025-01-09 08:02 UTC, DenTray commented on tests/EntityControlTraitTest.php
> +    protected string $mockedFillableDate;
is it required?

2025-01-09 12:24 UTC, yogyrton commented on tests/EntityControlTraitTest.php
> +    protected string $mockedFillableDate;
Yes
We use this in the [test ](https://github.com/RonasIT/laravel-helpers/pull/178/files#diff-c11daa4c78ecc23b20e082a0af5be370ac57e6769bc9be1f2d1222a83ff6c33dR267). In the model $timestamps = true, $fillable = ['creation_date'] and we check that the creation_date field is written to the database with our value, and the updated_date field is the default

2025-01-10 06:29 UTC, DenTray requested changes

2025-01-10 09:20 UTC, DenTray commented
@yogyrton please resolve conflicts

2025-01-13 09:15 UTC, DenTray requested changes

2025-01-13 09:15 UTC, DenTray commented on tests/support/Traits/SqlMockTrait.php
> +            $this->mockedFillableDate, 'test_name_1', $this->mockedNow,
as discussed, please just hardcode this value instead if using class property

2025-01-14 03:21 UTC, DenTray approved these changes

2025-01-14 03:21 UTC, merged