feat: add gt, lt, gte, lte filters
RonasIT/laravel-helpers pull request #86
Opened 2023-09-29 18:51 UTC by Goodmain

2023-10-02 16:37 UTC, DenTray requested changes

2023-10-02 16:37 UTC, DenTray commented on src/Traits/SearchTrait.php
> +        $sign = $strict ? '<' : '<=';
```suggestion
        $sign = ($strict) ? '<' : '<=';
```

2023-10-02 16:37 UTC, DenTray commented on src/Traits/SearchTrait.php
>          return $this;
```suggestion
        return $this->filterLess($field, $strict, $filterName);
```

2023-10-02 16:37 UTC, DenTray commented on src/Traits/SearchTrait.php
> +    public function filterLess(string $field, bool $strict = true, ?string $filterName = null): self
```suggestion
    public function filterLess(string $field, bool $isStrict = true, ?string $filterName = null): self
```

2023-10-02 16:37 UTC, DenTray commented on src/Traits/SearchTrait.php
>          return $this;
```suggestion
        return $this->filterGreater($field, $strict, $filterName);
```

2023-10-02 16:37 UTC, DenTray commented on src/Traits/SearchTrait.php
> +    public function filterGreater(string $field, bool $strict = true, ?string $filterName = null): self
```suggestion
    public function filterGreater(string $field, bool $isStrict = true, ?string $filterName = null): self
```

2023-10-03 16:02 UTC, Goodmain commented on src/Traits/SearchTrait.php
> +        $sign = $strict ? '<' : '<=';
Done

2023-10-03 16:02 UTC, Goodmain commented on src/Traits/SearchTrait.php
>          return $this;
Done

2023-10-03 16:03 UTC, Goodmain commented on src/Traits/SearchTrait.php
> +    public function filterLess(string $field, bool $strict = true, ?string $filterName = null): self
Done

2023-10-03 16:03 UTC, Goodmain commented on src/Traits/SearchTrait.php
>          return $this;
Done

2023-10-16 07:08 UTC, DenTray approved these changes

2023-10-16 07:08 UTC, merged