Update TestCase
RonasIT/laravel-helpers pull request #90
Opened 2023-10-24 07:16 UTC by yogyrton

2023-10-26 08:24 UTC, DenTray requested changes

2023-10-26 08:24 UTC, DenTray commented on src/Traits/FixturesTrait.php
> +        if ($exportMode || ($this instanceof TestCase && $this->globalExportMode)) {
```suggestion
        if ($exportMode || (property_exists($this, 'globalExportMode') && $this->globalExportMode)) {
```

2023-10-26 08:24 UTC, DenTray commented on tests/ExportTest.php
> +class ExportTest extends \Orchestra\Testbench\TestCase
please use class names aliases instead

```suggestion
class ExportTest extends TestCase
```

2023-10-26 11:17 UTC, DenTray requested changes

2023-10-26 11:17 UTC, DenTray commented on tests/ExportTest.php
> +<?php
please just implement new test case inside the FixtureTraitTest, which will call `unset($this->globalExportMode);` inside

2023-10-26 12:01 UTC, yogyrton commented
@DenTray Corrected. Please check it

2023-10-28 11:42 UTC, DenTray reviewed
@yogyrton it seems tests has beed failed. Could you please check it?

2023-10-29 09:32 UTC, yogyrton commented
@DenTray I updated it, becouse in this version $exportMode can be null,  but it’s not allowed

2023-10-30 06:55 UTC, yogyrton commented
@DenTray I checked and corrected it

2023-11-06 06:55 UTC, DenTray requested changes

2023-11-06 06:55 UTC, DenTray commented on src/Traits/FixturesTrait.php
> +use RonasIT\Support\Tests\TestCase;
```suggestion
```

2023-11-06 06:55 UTC, DenTray commented on tests/FixturesTraitTest.php
> +        $response = $this->getJsonFixture('get_fixture/export_fixture.json');
let's also use any existed fixture without creating new one

```suggestion
        $content = $this->getJsonFixture('get_fixture/export_fixture.json');
```

2023-11-07 04:58 UTC, DenTray requested changes

2023-11-07 04:58 UTC, DenTray commented on src/Traits/FixturesTrait.php
> +use RonasIT\Support\Tests\TestCase;
```suggestion
```

2023-11-07 04:58 UTC, DenTray commented on src/Traits/FixturesTrait.php
> +        if ($exportMode || (isset($this->globalFixtureExport) && $this->globalExportMode)) {
@KonstantinLapkovsky please check if this will works

```suggestion
        if ($globalExportMode ?? $exportMode) {
```

2023-11-07 04:58 UTC, DenTray commented on tests/FixturesTraitTest.php
> +        unset($this->globalExportMode);
```suggestion
        unset($this->globalExportMode);
```

2023-11-07 04:58 UTC, DenTray commented on tests/FixturesTraitTest.php
> +        $this->assertEqualsFixture('get_fixture/exists_fixture_comparison.json', $content);
please use exists fixture, no need to create a new one

2023-11-07 11:09 UTC, DenTray approved these changes

2023-11-07 11:09 UTC, merged